{% set name = "mapcat" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/mapcat-{{ version }}.tar.gz
  sha256: e0033c92d9959cdbd96339cffa51f47f6afea45c8c72f9128cf1282c135a5194

build:
  noarch: python
  entry_points:
    - actingest = mapcat.toolkit.act:main
    - mapcatmigrate = mapcat.helper:migrate
    - mapcatreset = mapcat.toolkit.reset:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - sqlmodel
    - sqlalchemy
    - aiosqlite
    - alembic
    - pydantic-settings
    - pixell
    - h5py
    - astropydantic

test:
  imports:
    - mapcat
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
    - actingest --help
    - mapcatmigrate --help
    - mapcatreset --help

about:
  home: https://pypi.org/project/mapcat/
  summary: The Depth-1 and Atomic MAP CATalog for the Simons Observatory.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - iparask
